name: Hillel weather app release

on: [push]
#  release:
#    types: [created]

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn --batch-mode install
      - name: Upload  Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: target/weather-app.jar